l_english:
WLS: "Kingdom of Wales"
WLS_neutrality: "Kingdom of Wales"
WLS_neutrality_DEF: "The Kingdom of Wales"
WLS_democratic: "Republic of Wales"
WLS_democratic_DEF: "The Republic of Wales"
WLS_fascism: "Welsh Free State"
WLS_communism: "People's Republic of Wales"
WLS_fascism_ADJ:0 "Welsh"
WLS_democratic_ADJ:0 "Welsh"
WLS_neutrality_ADJ:0 "Welsh"
WLS_communism_ADJ:0 "Welsh"
HKG_neutrality: "County of Hong Kong"
HKG_neutrality_DEF: "The County of Hong Kong"
HKG_democratic: "Republic of Hong Kong"
HKG_democratic_DEF: "The Republic of Hong Kong"
HKG_fascism: "City-State of Hong Kong"
HKG_communism: "Commune of Hong Kong"
HKG_fascism_ADJ:0 "Hong Kongese"
HKG_democratic_ADJ:0 "Hong Kongese"
HKG_neutrality_ADJ:0 "Hong Kongese"
HKG_communism_ADJ:0 "Hong Kongese"
MLA_fascism:0 "Unitary State of Malaya"
MLA_fascism_DEF:0 "The Unitary State of Malaya"
MLA_democratic:0 "Republic of Malaysia"
MLA_democratic_DEF:0 "The Republic of Malaysia"
MLA_neutrality:0 "Republic of Malaysia"
MLA_neutrality_DEF:0 "The Republic of Malaysia"
MLA_communism:0 "Malay People's Republic"
MLA_communism_DEF:0 "The Malay People's Republic"
MLA_fascism_ADJ:0 "Malaysian"
MLA_democratic_ADJ:0 "Malaysian"
MLA_neutrality_ADJ:0 "Malaysian"
MLA_communism_ADJ:0 "Malaysian"
SCO: "Kingdom of Scotland"
SCO_neutrality: "Kingdom of Scotland"
SCO_neutrality_DEF: "The Kingdom of Scotland"
SCO_democratic: "Republic of Scotland"
SCO_democratic_DEF: "The Republic of Scotland"
SCO_communism: "Socialist Republic of Scotland"
SCO_communism_DEF: "The Socialist Republic of Scotland"
SCO_fascism: "Scottish Free State"
SCO_fascism_DEF: "The Scottish Free State" 
SCO_ADJ: "Scottish"
SCO_fascism_ADJ: "Scottish"
SCO_communism_ADJ: "Scottish"
SCO_democratic_ADJ: "Scottish"
ZAM: "Zambia"
ZAM_neutrality: "Regent Government of Zambia"
ZAM_neutrality_DEF: "The Regent Government of Zambia"
ZAM_fascism: "Zambian Authoritative Republic"
ZAM_fascism_DEF: "The Zambian Authoritative Republic"
ZAM_communism: "Zambian Socialist Republic"
ZAM_ADJ: "Zambian"
ZAM_neutrality_ADJ: "Zambian"
ZAM_communism_ADJ: "Zambian"
ZAM_fascism_ADJ: "Zambian"
ZAM_democratic_ADJ: "Zambian"
MLW: "Malawi"
MLW_neutrality: "Malawiian Regency Government"
MLW_democratic: "The Malawiian Regency Government"
MLW_fascism: "Malawiian Authoritative State"
MLW_communism: "Malawiian Union"
MLW_ADJ: "Malawiian"
FRN: "Federetion of Rhodesia and Nyasaland"
FRN_neutrality: "Federation of Rhodesia and Nyasaland"
FRN_neutrality_DEF: "The Federation of Rhodesia and Nyasaland"
FRN_democratic: "Federation of Rhodesia and Nyasaland"
FRN_democratic_DEF: "The Federation of Rhodesia and Nyasaland"
FRN_communism: "Federation of Rhodesia and Nyasaland"
FRN_communism_DEF: "The Federation of Rhodesia and Nyasaland"
FRN_fascism: "Federation of Rhodesia and Nyasaland"
FRN_fascism_DEF: "The Federation of Rhodesia and Nyasaland"
FRN_ADJ: "Rhodesia-Nyasalander"
FRN_neutrality_ADJ: "Rhodesia-Nyasalander"
FRN_democratic_ADJ: "Rhodesia-Nyasalander"
FRN_communism_ADJ: "Rhodesia-Nyasalander"
FRN_fascism_ADJ: "Rhodesia-Nyasalander"
CSA_neutrality: "Confederate States of America"
CSA_neutrality_DEF: "The Confederate States of America"
CSA_democratic: "Confederate States of America"
CSA_democratic_DEF: "The Confederate States of America"
CSA_fascism: "White Ethnostate"
CSA_fascism_DEF: "The White Ethnostate"
CSA_communism: "Confederate Socialist States of America"
CSA_communism_DEF: "The Confederate Socialist States of America"
CSA_neutrality_ADJ: "Confederate"
CSA_communism_ADJ: "Confederate"
CSA_fascism_ADJ: "White"
CSA_democratic_ADJ: "Confederate"
DZG_neutrality: "Hanseatic City of Danzig"
DZG_neutrality_DEF: "The Hanseatic City of Daznig"
DZG_fascism: "Free City of Danzig"
DZG_fascism_DEF: "The Free City of Danzig"
DZG_democratic: "City-State of Danzig-Gdańsk"
DZG_democratic_DEF: "The City-State of Danzig-Gdańsk"
DZG_communism: "Danziger Commune"
DZG_communism_DEF: "The Danziger Commune"
DZG_neutrality_ADJ: "Hanseatic"
DZG_democratic_ADJ: "Danziger"
DZG_fascism_ADJ: "Danziger"
DZG_communism_ADJ: "Danziger"
RKM_fascism: "Reichskommissariat Moskowien"
RKM_fascism_DEF: "Reichskommissariat Moskowien"
RKM_democratic: "Reichskommissariat Moskowien"
RKM_democratic_DEF: "Reichskommissariat Moskowien"
RKM_communism: "Reichskommissariat Moskowien"
RKM_communism_DEF: "Reichskommissariat Moskowien"
RKM_neutrality: "Reichskommissariat Moskowien"
RKM_neutrality_DEF: "Reichskommissariat Moskowien"
RKM_fascism_ADJ: "German"
RKM_democratic_ADJ: "German"
RKM_neutrality_ADJ: "German"
RKM_communism_ADJ: "German"