l_english:
AST_UK_subject: "Dominion of Australia"
AST_UK_subject_DEF: "The Dominion of Australia"
NZL_UK_subject: "Dominion of New Zealand"
NZL_UK_subject_DEF: "The Dominion of New Zealand"
SAF_UK_subject: "Union of South Africa"
SAF_UK_subject_DEF: "The Union of South Africa"
SAF_UK_subject_colony: "Cape Colony"
SAF_UK_subject_colony_DEF: "Cape Colony"
CAN_UK_subject: "Dominion of Canada"
CAN_UK_subject_DEF: "The Dominion of Canada"
USA_ENG_subject: "Dominion of America"
USA_ENG_subject_DEF: "The Dominion of America"
USA_ENG_subject_colony: "Thirteen Colonies"
USA_ENG_subject_colony_DEF: "The Thirteen Colonies"
RAJ_UK_subject: "$OVERLORDADJ$ Raj"
RAJ_UK_subject_DEF: "$OVERLORDADJ$ Raj"
ZIM_ENG_subject: "$OVERLORDADJ$ Southern Rhodesia"
ZIM_ENG_subject_DEF: "$OVERLORDADJ$ Southern Rhodesia"
ZAM_UK_subject: "$OVERLORDADJ$ Northern Rhodesia"
ZAM_UK_subject_DEF: "$OVERLORDADJ$ Northern Rhodesia"
MLW_UK_subject: "$OVERLORDADJ$ Nyasaland"
MLW_UK_subject_DEF: "$OVERLORDADJ$ Nyasaland"
HKG_UK_subject: "$OVERLORDADJ$ Hong Kong"
HKG_UK_subject_DEF: "$OVERLORDADJ$ Hong Kong"
RAJ_fascistuk_subject: "$OVERLORDADJ$ Raj"
RAJ_fascistuk_subject_DEF: "$OVERLORDADJ$ Raj"
HKG_fascistuk_subject: "$OVERLORDADJ$ Hong Kong"
HKG_fascistuk_subject_DEF: "$OVERLORDADJ$ Hong Kong"
HKG_UK_ADJ: "$OVERLORDADJ$ Hongkongese"
HKG_UK_DEF: "$OVERLORDADJ$ Hong Kong"
HKG_fascistuk_ADJ: "$OVERLORDADJ$ Hongkongese"
HKG_fascsituk_DEF: "$OVERLORDADJ$ Hong Kong"
MLA_UK_subject: "$OVERLORDADJ$ Malaya"
MLA_UK_subject_DEF: "$OVERLORDADJ$ Malaya"
MLA_fascistuk_subject: "$OVERLORDADJ$ Malaya"
MLA_fascistuk_subject_DEF: "$OVERLORDADJ$ Malaya"
ZIM_fascistuk_subject: "$OVERLORDADJ$ Southern Rhodesia"
ZIM_fascistuk_subject_DEF: "$OVERLORDADJ$ Southern Rhodesia"
ZAM_fascistuk_subject: "$OVERLORDADJ$ Northern Rhodesia"
ZAM_fascistuk_subject_DEF: "$OVERLORDADJ$ Northern Rhodesia"
ZAM_fascistuk_subject: "$OVERLORDADJ$ Nyasaland"
ZAM_fascistuk_subject_DEF: "$OVERLORDADJ$ Nyasaland""
FRN_fascistuk_subject: "Federation of Rhodesia-Nyasaland"
FRN_fascistuk_subject: "The Federation of Rhodesia-Nyasaland"
VIN_FRA_subject: "$OVERLORDADJ$ Indochina"
VIN_FRA_subject_ADJ: "$OVERLORDADJ$ Indochinese"
VIN_FRA_subject_DEF: "$OVERLORDADJ$ Indochina"
BHN_subject: "Reichsprotektorat Böhmen und Mähren"
BHN_subject_DEF: "Reichsprotektorat Böhmen und Mähren"
BHN_ADJ: "German"
GGM_subject: "Generalgouvernement"
GGM_subject_DEF: "The Generalgouvernement"
GGM_subject_ADJ: "German"
RKU_subject: "Reichskommissariat Ukraine"
RKU_subject_DEF: "Reichskommissariat Ukraine"
RKU_subject_ADJ: "German"
RKO_subject: "Reichskommissariat Ostland"
RKO_subject_DEF: "Reichskommissariat Ostland"
RKO_subject_ADJ: "German"
RKK_subject: "Reichskommissariat Kaukasus"
RKK_subject_DEF: "Reichskommissariat Kaukasus"
RKK_subject_ADJ: "German"
RGB_subject: "Republic of Great Britain"
RGB_subject_DEF: "The Republic of Great Britain"
RGB_subject_ADJ: "British"

PRC_CSR_communism: "Chinese Soviet Republic"
PRC_CSR_communism_DEF: "The Chinese Soviet Republic"
PRC_FRONT_communism: "Communist China"
PRC_FRONT_communism_DEF: "Communist China"
GBR: "Great Britain"
GBR_democratic: "Kingdom of Great Britain"
GBR_democratic_DEF: "The Kingdom of Great Britain"
GBR_neutrality: "Kingdom of Great Britain"
GBR_neutrality_DEF: "The Kingdom of Great Britain"
ENG_ENG_neutrality: "Kingdom of England"
ENG_ENG_neutrality_DEF: "The Kingdom of England"
ENG_ENG_democratic: "Kingdom of England"
ENG_ENG_democratic_DEF: "The Kingdom of England"
ENG_ENG_communism: "Union of England"
ENG_ENG_communism_DEF: "The Union of England"
ENG_ENG_fascism: "English Empire"
ENG_ENG_fascism_DEF: "The English Empire"
ENG_ENG_neutrality_ADJ: "English"
ENG_ENG_fascism_ADJ: "English"
ENG_ENG_democratic_ADJ: "English"
ENG_ENG_communism_ADJ: "English"
BYZ: "Byzantine Empire"
BYZ_neutrality: "Byzantine Empire"
BYZ_neutrality_DEF: "The Byzantine Empire"
BYZ_fascism: "Byzantine Empire"
BYZ_fascism_DEF: "The Byzantine Empire"
BYZ_democratic: "Roman Republic"
BYZ_democratic_DEF: "The Roman Republic"
BYZ_communism: "Aegean Commune"
BYZ_communism_DEF: "The Aegan Commune"
BYZ_neutrality_ADJ: "Byzantine"
BYZ_fascism_ADJ: "Byzantine"
BYZ_democratic_ADJ: "Roman"
BYZ_communism_ADJ: "Aegean"
OTT: "Ottoman Empire"
OTT_fascism: "Ottoman Empire"
OTT_fascism_ADJ: "Ottoman"
OTT_fascism_DEF: "The Ottoman Empire"
OTT_neutrality: "Ottoman Empire"
OTT_neutrality_DEF: "The Ottoman Empire"
OTT_neutrality_ADJ: "Ottoman"
