l_english:
 super_extreme: "Anti-Extremism Measures"
 ENG_overseas_comrades: "Overseas Influence"
 revolution_global: "Global Revolution"
 RHODESIA: "Rhodesian Autonomy"
 young_republic: "Young Republic"
 autocratic_advocate: "Autocratic Advocate"
 traditionalist_clubs: "Traditionalist Clubs"
 generic_autocratic_advocate: "Paternal Autocratic Advisor"
 ROM_carol_II: "King Carol II"
 ROM_michael_i: "King Michael I"
 GRE_george_ii: "King George II"
 GRE_georgios_i: "Basileus Georgios I"
 GER_antisemitism: "Anti-Semitic Policy"
 GER_antisemitism_desc: "The Jewish population of this nation are treated as second-class citizens, suffering from terrible living conditions in addition to frequent abuse and harassment."
 POL_ghettos: "Ethnic Ghettoes"
 POL_ghettos_desc: "Ghettoes of those deemed "undesirable" by the NSDAP exist within this nation. Those confined to such ghettoes are forced to live with abhorrent conditions and are often treated with extreme abuse."
 POL_arbeiter: "Zivilarbeiter"
 POL_arbeiter_desc: "The native Polish population is not deemed racially fit for service in the Wehrmacht or Schutzstaffel. The population is instead conscripted into forced labour in armaments production across the Reich."
 GER_OST: "Generalplan Ost"
 GER_OST_desc: "The native Slavic population has been marked for extermination through forced labour and execution, making way for a wave of German colonists to repopulate the territory."
 GER_OST_2: "Generalplan Ost"
 GER_OST_2_desc: "The native Slavic population has been marked for extermination through forced labour and execution, making way for a wave of German colonists to repopulate the territory."
 GER_OST_3: "Generalplan Ost"
 GER_OST_3_desc: "The native Slavic population has been marked for extermination through forced labour and execution, making way for a wave of German colonists to repopulate the territory."
 GER_OST_4: "Generalplan Ost"
 GER_OST_4_desc: "The native Slavic population has been marked for extermination through forced labour and execution, making way for a wave of German colonists to repopulate the territory."
 GER_OST_5: "Generalplan Ost"
 GER_OST_5_desc: "The native Slavic population has been marked for extermination through forced labour and execution, making way for a wave of German colonists to repopulate the territory."
 GER_OST_6: "Generalplan Ost"
 GER_OST_6_desc: "The native Slavic population has been marked for extermination through forced labour and execution, making way for a wave of German colonists to repopulate the territory."

 UKR_collab: "Ukrainian Collaborationism"
 UKR_collab_desc: "After having endured decades of harsh treatment and oppression under Soviet rule, much of the Ukrainian populace view the advancing German forces as liberators."
 afghan_resilience: "Afghan Resilience"
 afghan_resilience_desc: "After enduring against centuries of foreign invasions from the global superpowers, Afghanistan has always come out on top. Any invader would be wise to take this into consideration before launching an attack against this nation."
 east_bolshevik: "The Bolshevik Threat"
 east_bolshevik_desc: "This nation is fearful of the constant threat of invasion and subversion posed by the neighbouring Soviet Union; it's people are unwilling to submit without a fight."
 besieged: "Besieged"
 besieged_desc: "Besieged by totalitarian foes from both east and west, this nation is being forced to search further afield for new alliances. They will likely discover new friendships amongst Europe's liberal democracies."