l_english:
 ENG_me_intervention: "Middle Eastern Intervention"
 ENG_me_intervention_USA: "Intervening in the Middle East"
 ENG_me_intervention_IRQ_PER: "Threatened Intervention!"
 uk_leanings: "Strenghthened Ties"
 CABLE_STREET: "The Battle of Cable Street has happened"
 uk_irish_rec_opinion: "Claimed Our Territory!"
 ENG_irish_fortify: "Fortified the Irish Border"
 ENG_irish_claims: "Claimed Ireland"
 ENG_breton_claims: "Claimed Britanny"
 ENG_france_war: "Threatened War on France"
 ENG_ireland_war: "Threatened War on Ireland"
 ENG_usa_claims: "Claimed the East Coast"
 ENG_usa_war: "Threatened War on the United States"
 ENG_nationalist_spain_ally: "Spain gets invited into our faction"
 uk_fascism_influences: "BUF Influence"
 uk_communism_influences: "CPGB Influence"
 ENG_abolish_monarchy: "This action will depose the King"