l_english:
WLS_fascism_party: "Byddin Rhyddid Cymru"
WLS_democratic_party: "Plaid Cymru" 
WLS_neutrality_party: "House of Aberffraw"
WLS_communism_party: "CPW"
WLS_communism_party_long: "Communist Party of Wales"
HKG_fascism_party: "Chinese Committee"
HKG_democratic_party: "Reform Club"
HKG_neutrality_party: "Colonial Government"
HKG_communism_party: "Seamen's Union"
MLA_neutrality_party: "Colonial Government"
MLA_fascism_party: "Pan-Oceanic Union"
MLA_democratic_party: "United Malays National Organisation"
MLA_communism_party: "Malayan Communist Party" 
SCO_democratic_party: "Scottish National Party"
SCO_fascism_party: "SDFP"
SCO_fascism_party_long: "Scottish Democratic Fascist Party"
SCO_communism_party: "Communist Labour Party"
SCO_neutrality_party: "Jacobites"
PRC_communism_party: "CPC"
PRC_communism_party_long: "Communist Party of China"
PRC_neutrality_party: "Qing Dynasty"
PRC_fascism_party: "Kuomintang"
PRC_democratic_party: "China Democratic League"
ZIM_neutrality_party: "Colonial Government"
ZIM_democratic_party: "Rhodesian Front"
ZIM_communism_party: "ZANU"
ZIM_communism_party_long: "Zimbabwe African National Union"
ZIM_fascism_party: "Military Regime"
ZAM_neutrality_party: "Colonial Government"
ZAM_democratic_party: "ZANC"
ZAM_democratic_party_long: "Zambian African National Congress"
ZAM_communism_party: "ZAPU"
ZAM_communism_party_long: "Zambian African People's Union"
ZAM_fascism_party: "Zambian Vanguard"
MLW_democratic_party: "Malawi Congress Party"
MLW_communism_party: "MPLP"
MLW_communism_party_long: "Malawiian People's Liberation Party"
MLW_fascism_party: "MNUP"
MLW_fascism_party: "Malawiian National Unity Party"
MLW_neutrality_party: "Colonial Government"
FRN_neutrality_party: "Colonial Government"
FRN_communism_party: "ZANU"
FRN_communism_party_long: "Zimbabwe African National Union"
FRN_fascism_party: "Military Regime"
FRN_democratic_party: "Rhodesian Front"
CSA_neutrality_party: "Confederate States Military"
CSA_democratic_party: "Democratic Party"
CSA_communism_party: "CPCSA"
CSA_communism_party_long: "Communist Party of the Confederate States of America"
CSA_fascism_party: "KKK"
CSA_fascism_party_long: "Ku Klux Klan"
DZG_fascism_party: "NSDAP"
DZG_fascism_party_long: "Nationalsozialistische Deutsche Arbeiterpartei"
DZG_communism_party: "KPD"
DZG_communism_party_long: "Kommunistische Partei Danzig"
DZG_neutrality_party: "DNVP"
DZG_neutrality_party_long: "Deutschnationale Volkspartei"
DZG_democratic_party: "SPD"
DZG_democratic_party_long: "Sozialdemokratische Partei Danzig"
RKM_neutrality_party: "DNVP"
RKM_neutrality_party_long: "Deutschnationale Volkspartei"
RKM_fascism_party:0 "NSDAP"
RKM_fascism_party_long:0 "Nationalsozialistische Deutsche Arbeiterpartei"
RKM_communism_party:0 "KPD"
RKM_communism_party_long: "Kommunistische Partei Deutschlands"
RKM_democratic_party:1 "Zentrum"
RKM_democratic_party_long: "Deutsche Zentrumspartei"
