l_polish:
WLS_fascism_party: "Byddin Rhyddid Cymru"
WLS_democratic_party: "Plaid Cymru" 
WLS_neutrality_party: "Dynastia Aberffraw"
WLS_communism_party: "CPW"
WLS_communism_party_long: "Walijska Partia Komunistyczna"
HKG_fascism_party: "Chińska Komisja"
HKG_democratic_party: "Klub Reformy"
HKG_neutrality_party: "Rząd Kolonialny"
HKG_communism_party: "Związek Marynarzy"
MLA_neutrality_party: "Rząd Kolonialny"
MLA_fascism_party: "Unia Oceańska"
MLA_democratic_party: "Krajowa Organizacja Malaji"
MLA_communism_party: "Partia Komunistyczna Malaji" 
SCO_democratic_party: "Szkocka Partia Nacjonalistyczna"
SCO_fascism_party: "SDFP"
SCO_fascism_party_long: "Szkocka Partia Demokratyczno-Faszystowska"
SCO_communism_party: "Partia Roboczo-Komunistyczna"
SCO_neutrality_party: "Jakobici"
PRC_communism_party: "CPC"
PRC_communism_party_long: "Komunistyczna Partia Chin"
ZIM_neutrality_party: "Rząd Kolonialny"
ZIM_democratic_party: "Front Rodezyjski"
ZIM_communism_party: "ZANU"
ZIM_communism_party_long: "Unia Nacjonalistyczno-Afrykańska w Zimbabwe"
ZIM_fascism_party: "Reżim Wojskowy"
ZAM_neutrality_party: "Rząd Kolonialny"
ZAM_democratic_party: "ZANC"
ZAM_democratic_party_long: "Kongres Nacjonalistyczna Zambi"
ZAM_communism_party: "ZAPU"
ZAM_communism_party_long: "Unia Ludowa w Zambi"
ZAM_fascism_party: "Awangarda Zambijska"
MLW_democratic_party: "Partia Kongrosowa Malawi"
MLW_communism_party: "MPLP"
MLW_communism_party_long: "Partia Wybawienia Ludowego"
MLW_fascism_party: "MNUP"
MLW_fascism_party: "Malawijska Partia Narodowej Unii"
MLW_neutrality_party: "Rząd Kolonialny"
FRN_neutrality_party: "Colonial Government"
FRN_communism_party: "ZANU"
FRN_communism_party_long: "Unia Nacjonalistyczno-Afrykańska w Zimbabwe"
FRN_fascism_party: "Reżim Wojskowy"
FRN_democratic_party: "Front Rodezyjski"


